# Generated by Django 5.0.2 on 2024-05-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_email_confirmed_alter_myuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='email_confirmed',
        ),
    ]
