# Generated by Django 5.0.2 on 2024-06-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recettes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recettecomment",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
